### PR TITLE
More Extensive Writing Support

### PR DESCRIPTION
**Pull request by jcdickinson**
We implemented the other writers, e.g. Class/Interface/etc. Somewhat rough in some places so cherry-pick as you see fit :).

### CODE REVIEW

**Comment by jbevain** [comment]
As it is, it's indeed not mergeable. The changes are:
- Not following Mono's coding guidelines, at all.
- Hard to read because of whitespace changes, again, please follow the guidelines.
- Not backed with tests.

Thanks.

**Comment by migueldeicaza** [comment]
The coding guidelines:

http://www.mono-project.com/Coding_Guidelines

In general, when contribute to an open source project, it is good to follow the etiquette:

http://tirania.org/blog/archive/2010/Dec-31.html

**Comment by jcdickinson** [comment]
Cool I'll branch it and fix up the code whitespacing and send it back your way.

**Comment by jcdickinson** [comment]
Is there any way I can validate the merge-ability my side before sending it to you?

**Comment by jbevain** [comment]
The best way to proceed is to do small and targeted pull requests, that can be easily reviewed. See https://github.com/mono/cecil/pull/1 for instance. Thanks!

**Pull request closed without merging**
