### PR TITLE
Cecil.Decompiler improvements

### PR DESCRIPTION
**Pull request by chkn**
Hi,
Miguel's recent blog post about Cecil.Decompiler reminded me that I'd hacked on it a bit recently. Hope these modest changes are helpful to anyone.
-Alex

### CODE REVIEW

**Comment by jbevain** [comment]
I've added inline comments, but this is looking good. Some tests would be cool. Thanks!

**Comment by chkn** [comment]
Thanks for reviewing this so quickly! I think I addressed all your comments. I got the test suite running and most everything passes, except for a couple tests where the comparison is reversed in the ternary (though the code is still equivalent to the original). I'm not very experienced at writing tests, but I gave it a shot writing one for the new delegate functionality. Let me know if there's anything else I can do to help get this committed. Thanks again!

**Comment by jbevain** [comment]
This is looking good. Just make sure the code generator is modified to properly generate MethodAddressExpression and we'll get that in.

**Comment by chkn** [comment]
Is this correct? My boo environment is giving me trouble

**Comment by akoeplinger** [comment]
We don't monitor this repository anymore and are marking it read-only, please report any issues upstream. Thank you!

**Pull request closed without merging**
